 import * as c from "./constants";
 import { ACCENT_TYPE as accent, CLASS_TYPE as classes } from "./enum-types";

 export const helpComments = [
    {
        "category": c.parisyllabicFeminineI,
        "help": "All nouns of this category are accented in the last syllable in the plural genitive. Some paroxytone and proparoxytone nouns of this category don't form the plural genitive. These are usually abstract or uncountable nouns"
    },
    {
        "category": c.parisyllabicMasculineOs,
        "help": "Some parisyllabic proparoxytone -ος ending nouns move their accent one position to the right in the genitive case (singular and plural) and in the plural accusative"
    },
    {
        "category": c.parisyllabicMasculineIs,
        "help": "In the plural genitive, all parisyllabic masculine -ης ending nouns are accented in the last syllable"
    },
    {
        "category": c.parisyllabicNeuterO,
        "help": "Some proparoxytone nouns move their accent mark one position to the right in the genitive case (singular and plural). Trisyllabic proparoxytone place names usually behave like that"
    },
    {
        "category": c.parisyllabicNeuterOs,
        "help": "Nominative and accusative move their accent one position to the right. All the nouns of this group move their accent to the last syllable in the plural genitive case"
    },
    {
        "category": c.parisyllabicFeminineOs,
        "help": "The proparoxytone nouns move their accent mark one position to the right in the genitive case (singular and plural) and in the plural accusative"
    },
]

export const questions = [
    { "element": "κλειδ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "key", "moveToLast": true },
    { "element": "αρν", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "lamb", "moveToLast": true },
    { "element": "νησ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "island", "moveToLast": true },
    { "element": "πουλ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "bird", "moveToLast": true },
    { "element": "παιδ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "child, kid", "moveToLast": true },
    { "element": "σκοιν", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "rope", "moveToLast": true },
    { "element": "σφυρ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "hammer", "moveToLast": true },
    { "element": "χαρτ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "paper / document", "moveToLast": true },
    { "element": "ψωμ", "category": c.parisyllabicNeuter, "accent": accent.oxytone, "translation": "bread", "moveToLast": true },
    { "element": "ράφ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "shelf", "moveToLast": true },
    { "element": "αγόρ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "boy", "moveToLast": true },
    { "element": "αηδόν", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "nightingale", "moveToLast": true },
    { "element": "θυμάρ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "thyme", "moveToLast": true },
    { "element": "καλοκαίρ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "summer", "moveToLast": true },
    { "element": "κορίτσ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "girl / girlfriend", "moveToLast": true },
    { "element": "λουλούδ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "flower", "moveToLast": true },
    { "element": "παπούτσ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "shoe", "moveToLast": true },
    { "element": "σπίτ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "house / home", "moveToLast": true },
    { "element": "τραγούδ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "song", "moveToLast": true },
    { "element": "χέρ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "hand / arm", "moveToLast": true },
    { "element": "χιόν", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "snow", "moveToLast": true },
    { "element": "ψαλτήρ", "category": c.parisyllabicNeuter, "accent": accent.paroxytone, "translation": "hymnbook", "moveToLast": true },
    { "element": "φίλντισ", "category": c.parisyllabicNeuter, "accent": accent.proparoxytone, "translation": "ivory", "moveToLast": true },
    { "element": "βοηθ", "category": c.secondConjugationVerb, "translation": "to help", "class": classes.first },
    { "element": "εξυπηρετ", "category": c.secondConjugationVerb, "translation": "to serve, to be of service", "class": classes.second  },
    { "element": "φων", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "voice" },
    { "element": "αλλαγ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "change", "moveToLast": true },
    { "element": "αρχ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "beginning, start", "moveToLast": true },
    { "element": "Αφρικ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "Africa", "moveToLast": true },
    { "element": "γραμμ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "line", "moveToLast": true },
    { "element": "διακοπ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "interruption, break, disconnection, pause, termination", "moveToLast": true },
    { "element": "εκλογ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "election", "moveToLast": true },
    { "element": "μηχαν", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "machine, engine", "moveToLast": true },
    { "element": "τιμ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "price, honor", "moveToLast": true },
    { "element": "ψυχ", "category": c.parisyllabicFeminineI, "accent": accent.oxytone, "translation": "soul, psyche", "moveToLast": true },
    { "element": "κόρ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "daughter, young woman, maiden, eye pupil", "moveToLast": true },
    { "element": "αγάπ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "love", "moveToLast": true },
    { "element": "άκρ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "edge", "moveToLast": true },
    { "element": "βιβλιοθήκ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "bookcase, library", "moveToLast": true },
    { "element": "βλάβ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "amage, malfunction", "moveToLast": true },
    { "element": "βρύσ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "tap, water fountain", "moveToLast": true },
    { "element": "γνώμ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "opinion", "moveToLast": true },
    { "element": "δάφν", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "laurel", "moveToLast": true },
    { "element": "δίκ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "trial", "moveToLast": true },
    { "element": "επιστήμ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "science", "moveToLast": true },
    { "element": "Ευρώπ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "Europe", "moveToLast": true },
    { "element": "ζέστ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "heat", "moveToLast": true },
    { "element": "λάσπ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "mud", "moveToLast": true },
    { "element": "μέθ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "drunkenness", "moveToLast": true },
    { "element": "μέσ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "middle, waist", "moveToLast": true },
    { "element": "μύτ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "nose, point, peak", "moveToLast": true },
    { "element": "νίκ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "victory, win", "moveToLast": true },
    { "element": "στάν", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "pen for animals", "moveToLast": true },
    { "element": "στρώσ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "layer", "moveToLast": true },
    { "element": "τέχν", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "art", "moveToLast": true },
    { "element": "τόλμ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "boldness", "moveToLast": true },
    { "element": "φήμ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "rumor, fame, reputation", "moveToLast": true },
    { "element": "χάρ", "category": c.parisyllabicFeminineI, "accent": accent.paroxytone, "translation": "grace, favor, sak", "moveToLast": true },
    { "element": "ζάχαρ", "category": c.parisyllabicFeminineI, "accent": accent.proparoxytone, "translation": "sugar", "moveToLast": true },
    { "element": "Άρτεμ", "category": c.parisyllabicFeminineI, "accent": accent.proparoxytone, "translation": "Artemis", "moveToLast": true },
    { "element": "κάμαρ", "category": c.parisyllabicFeminineI, "accent": accent.proparoxytone, "translation": "boudoir, room", "moveToLast": true },
    { "element": "κάππαρ", "category": c.parisyllabicFeminineI, "accent": accent.proparoxytone, "translation": "caper", "moveToLast": true },
    { "element": "σίκαλ", "category": c.parisyllabicFeminineI, "accent": accent.proparoxytone, "translation": "rye", "moveToLast": true },
    { "element": "γιατρ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "doctor" },
    { "element": "βαθμ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "grade, degree" },
    { "element": "θε", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "god" },
    { "element": "καιρ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "time, weather" },
    { "element": "λα", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "people of a country" },
    { "element": "λογαριασμ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "bill, calculation" },
    { "element": "ουραν", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "sky" },
    { "element": "σεισμ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "earthquake" },
    { "element": "σολομ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "salmon" },
    { "element": "χωρισμ", "category": c.parisyllabicMasculineOs, "accent": accent.oxytone, "translation": "separation" },
    { "element": "φίλ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "friend" },
    { "element": "δρόμ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "road, street" },
    { "element": "γάμ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "marriage, wedding" },
    { "element": "ήλι", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "sun" },
    { "element": "κήπ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "garden" },
    { "element": "νόμ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "law" },
    { "element": "ταχυδρόμ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "postman" },
    { "element": "τόπ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "place, location" },
    { "element": "χρόν", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "time, year" },
    { "element": "χώρ", "category": c.parisyllabicMasculineOs, "accent": accent.paroxytone, "translation": "space, place" },
    { "element": "χωματόδρομ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "dirt road" },
    { "element": "ανεμόμυλ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "windmill" },
    { "element": "ανήφορ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "uphill" },
    { "element": "αντίλαλ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "echo" },
    { "element": "αυλόγυρ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "yard, patio" },
    { "element": "καλόγερ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "monk" },
    { "element": "κατήφορ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "downhill" },
    { "element": "υπάλληλ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "employee" },
    { "element": "άνθρωπ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "human, man" },
    { "element": "δήμαρχ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "mayor" },
    { "element": "έμπορ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "merchant" },
    { "element": "έφορ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "tax collector" },
    { "element": "άνεμ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "wind" },
    { "element": "διάδρομ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "corridor, treadmill" },
    { "element": "όροφ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "floor, story, level" },
    { "element": "πόλεμ", "category": c.parisyllabicMasculineOs, "accent": accent.proparoxytone, "translation": "war" },
    { "element": "μαθητ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "student" },
    { "element": "αγοραστ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "buyer" },
    { "element": "αθλητ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "athlete" },
    { "element": "βουλευτ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "member of the parliament" },
    { "element": "δανειστ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "lender" },
    { "element": "διευθυντ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "principal, manager, director" },
    { "element": "δικαστ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "judge" },
    { "element": "λογιστ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "accountant" },
    { "element": "ποιητ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "poet" },
    { "element": "σπουδαστ", "category": c.parisyllabicMasculineIs, "accent": accent.oxytone, "translation": "university student" },
    { "element": "βιβλιοπώλ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "bookseller" },
    { "element": "γυμνασιάρχ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "middle school headmaster" },
    { "element": "δεσπότ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "despot, bishop" },
    { "element": "επιβάτ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "passenger" },
    { "element": "ναύτ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "seaman, sailor" },
    { "element": "πολίτ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "citizen" },
    { "element": "ράφτ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "tailor" },
    { "element": "στρατιώτ", "category": c.parisyllabicMasculineIs, "accent": accent.paroxytone, "translation": "soldier" },
    { "element": "κινητ", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "mobile phone" },
    { "element": "βουν", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "mountain" },
    { "element": "μαγειρει", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "galley, restaurant or cafeteria kitchen" },
    { "element": "Μεξικ", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "Mexico" },
    { "element": "νερ", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "water" },
    { "element": "νοικοκυρι", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "household" },
    { "element": "παγωτ", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "ice cream" },
    { "element": "ποσ", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "amount" },
    { "element": "φτερ", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "wing, feather, blade" },
    { "element": "χωρι", "category": c.parisyllabicNeuterO, "accent": accent.oxytone, "translation": "village" },
    { "element": "πεδί", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "field" },
    { "element": "αστεροσκοπεί", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "observatory" },
    { "element": "βιβλί", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "book" },
    { "element": "δέντρ", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "tree" },
    { "element": "θηρί", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "beast" },
    { "element": "θρανί", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "school desk" },
    { "element": "πεύκ", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "pine tree" },
    { "element": "Τορίν", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "Turin" },
    { "element": "υπουργεί", "category": c.parisyllabicNeuterO, "accent": accent.paroxytone, "translation": "ministry" },
    { "element": "σύννεφ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "cloud", "moveAccent": false },
    { "element": "αμύγδαλ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "almond", "moveAccent": false },
    { "element": "δάχτυλ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "finger", "moveAccent": false },
    { "element": "σέλιν", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "celery", "moveAccent": false },
    { "element": "σίδερ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "iron (appliance)", "moveAccent": false },
    { "element": "τριαντάφυλλ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "rose", "moveAccent": false },
    { "element": "χαμόκλαδ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "branch growing near the ground, bush", "moveAccent": false },
    { "element": "αυτοκίνητ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "car", "moveAccent": true },
    { "element": "άλογ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "horse", "moveAccent": true },
    { "element": "άτομ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "atom, person, individual", "moveAccent": true },
    { "element": "δωμάτι", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "room", "moveAccent": true },
    { "element": "έπιπλ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "piece of furniture", "moveAccent": true },
    { "element": "θέατρ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "theater", "moveAccent": true },
    { "element": "Καλάβρυτ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "Kalavrita town", "moveAccent": true },
    { "element": "κείμεν", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "text", "moveAccent": true },
    { "element": "κύπελλ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "cup, goblet", "moveAccent": true },
    { "element": "μέτωπ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "forehead, battlefront", "moveAccent": true },
    { "element": "όργαν", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "organ, instrument, tool", "moveAccent": true },
    { "element": "πρόσωπ", "category": c.parisyllabicNeuterO, "accent": accent.proparoxytone, "translation": "face, person, character", "moveAccent": true },
    { "element": "είδ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "style, type, kind genre, article, item", "moveAccent": false },
    { "element": "άλσ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "grove", "moveAccent": false },
    { "element": "βάρ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "weight", "moveAccent": false },
    { "element": "βέλ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "arrow", "moveAccent": false },
    { "element": "γέν", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "gender, genus", "moveAccent": false },
    { "element": "δάσ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "forest", "moveAccent": false },
    { "element": "λάθ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "mistake, error", "moveAccent": false },
    { "element": "μέρ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "place, part, spot", "moveAccent": false },
    { "element": "κράτ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "nation, state", "moveAccent": false },
    { "element": "τέλ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "end, ending, fee", "moveAccent": false },
    { "element": "χρέ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "debt", "moveAccent": false },
    { "element": "μέγεθ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "size", "moveAccent": true },
    { "element": "έδαφ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "ground, soil, land, territory", "moveAccent": true },
    { "element": "στέλεχ", "category": c.parisyllabicNeuterOs, "accent": accent.paroxytone, "translation": "executive, stub, stem, strain", "moveAccent": true },
    { "element": "ηθοποι", "category": c.parisyllabicFeminineOs, "accent": accent.oxytone, "translation": "actor, actress", "moveAccent": false },
    { "element": "ατραπ", "category": c.parisyllabicFeminineOs, "accent": accent.oxytone, "translation": "path, trail (dated)", "moveAccent": false },
    { "element": "θαλαμηγ", "category": c.parisyllabicFeminineOs, "accent": accent.oxytone, "translation": "yacht", "moveAccent": false },
    { "element": "κιβωτ", "category": c.parisyllabicFeminineOs, "accent": accent.oxytone, "translation": "ark", "moveAccent": false },
    { "element": "οδ", "category": c.parisyllabicFeminineOs, "accent": accent.oxytone, "translation": "street", "moveAccent": false },
    { "element": "στενωπ", "category": c.parisyllabicFeminineOs, "accent": accent.oxytone, "translation": "neck of the woods", "moveAccent": false },
    { "element": "λεωφόρ", "category": c.parisyllabicFeminineOs, "accent": accent.paroxytone, "translation": "avenue", "moveAccent": false },
    { "element": "άμμ", "category": c.parisyllabicFeminineOs, "accent": accent.paroxytone, "translation": "sand", "moveAccent": false },
    { "element": "Βίβλ", "category": c.parisyllabicFeminineOs, "accent": accent.paroxytone, "translation": "Bible", "moveAccent": false },
    { "element": "νήσ", "category": c.parisyllabicFeminineOs, "accent": accent.paroxytone, "translation": "sland (scholarly)", "moveAccent": false },
    { "element": "ψήφ", "category": c.parisyllabicFeminineOs, "accent": accent.paroxytone, "translation": "vote, ballot", "moveAccent": false },
    { "element": "έξοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "exit, exodus, outing", "moveAccent": true },
    { "element": "άνοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "ascend, rise", "moveAccent": true },
    { "element": "διαγώνι", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "diagonal", "moveAccent": true },
    { "element": "διάλεκτ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "dialect", "moveAccent": true },
    { "element": "εγκύκλι", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "bulletin", "moveAccent": true },
    { "element": "ίσοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "entrance", "moveAccent": true },
    { "element": "επέτει", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "anniversary", "moveAccent": true },
    { "element": "κάθοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "descent", "moveAccent": true },
    { "element": "Κόρινθ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "Corinth", "moveAccent": true },
    { "element": "μέθοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "method", "moveAccent": true },
    { "element": "παράγραφ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "paragraph", "moveAccent": true },
    { "element": "περίοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "period", "moveAccent": true },
    { "element": "πρόοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "progress, advancement, progression", "moveAccent": true },
    { "element": "σύνοδ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "meeting, conference", "moveAccent": true },
    { "element": "χερσόνησ", "category": c.parisyllabicFeminineOs, "accent": accent.proparoxytone, "translation": "peninsula", "moveAccent": true },
    { "element": "καφετ", "category": c.isIaIAdjective, "translation": "brownish" },
    { "element": "βυσσιν", "category": c.isIaIAdjective, "translation": "crimson" },
    { "element": "κανελ", "category": c.isIaIAdjective, "translation": "cinnamon (color)" },
    { "element": "μαβ", "category": c.isIaIAdjective, "translation": "purple" },
    { "element": "μενεξεδ", "category": c.isIaIAdjective, "translation": "lilac (color)" },
    { "element": "ουραν", "category": c.isIaIAdjective, "translation": "sky blue" },
    { "element": "πορτοκαλ", "category": c.isIaIAdjective, "translation": "orange (color)" },
    { "element": "σταχτ", "category": c.isIaIAdjective, "translation": "gray ash (color)" },
    { "element": "χρυσαφ", "category": c.isIaIAdjective, "translation": "golden (color)" },
];
