export const sections = [
  { key: 0, name: 'Plural of -ος, -α, and -ο', route: 'plurals' },
  { key: 1, name: 'Subjunctive', route: 'subjunctive' },
  { key: 2, name: 'Telling Time', route: 'time' },
  { key: 3, name: 'Imperative', route: 'imperative' },
  { key: 4, name: 'Adjective Endings (-ος, -η, -ο)', route: 'adjective' },
  { key: 5, name: 'υπάρχει/υπάρχουν and αρέσει/αρέσουν', route: 'there-is' },
  { key: 6, name: 'Accusative Weak Personal Pronouns', route: 'accusative-weak' },
  { key: 7, name: 'Adjectives Versus Adverbs', route: 'advebs' },
  { key: 8, name: 'Genitive Weak Personal Pronouns', route: 'genitive-weak' },
  { key: 9, name: 'Use of the Indefinite Article in Modern Greek', route: 'indefinite-article' },
  { key: 10, name: 'Numbers (Singular and Plural) in Nouns', route: 'numbers-in-nouns' },
  { key: 11, name: 'Cases and Especially the Genitive Case of Nouns', route: 'genitive-case-of-nouns' },
  { key: 12, name: 'Vocative Case of Nouns', route: 'vocative' },
  { key: 13, name: 'Irregular Adjective πολύς/πολλοί', route: 'irregular-adjetive' },
  { key: 14, name: 'Accusative Case of Nouns Used with έχω', route: 'accusative' },
  { key: 15, name: 'First Person, Singular and Plural of the Verb έχω', route: 'to-have-first-person' },
  { key: 16, name: 'Second and Third Person Forms of the Verb έχω', route: 'to-have-second-and-third-person' },
  { key: 17, name: 'Past Tense of the Verb είμαι', route: 'to-be-past-tense' },
  { key: 18, name: 'είχα, the Past Tense of the Verb έχω', route: 'to-have-past-tense' },
  { key: 19, name: 'Past Tense of Common Greek Verbs', route: 'past-tenses' },
  { key: 20, name: 'Definite Article of Nouns', route: 'definite-article' },
  { key: 21, name: 'Declensions', route: 'declensions' },
  { key: 24, name: 'Comparing Adjectives with the Comparative Degree', route: 'comparative-degree' },
  { key: 25, name: 'Superlative Degree of Adjectives', route: 'superlative-degree' },
]